// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARUzuHCHEhYD5LUe6sQcFSGvTdDb6VmRg',
    appId: '1:1073745768330:web:67a77cd731689cca976273',
    messagingSenderId: '1073745768330',
    projectId: 'campuscar-fa0ef',
    authDomain: 'campuscar-fa0ef.firebaseapp.com',
    storageBucket: 'campuscar-fa0ef.appspot.com',
    measurementId: 'G-YWDV703VWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNGCtGaHkJPjgn_jqBZMqY321AuwHab0c',
    appId: '1:1073745768330:android:2cc89d9feaba92b6976273',
    messagingSenderId: '1073745768330',
    projectId: 'campuscar-fa0ef',
    storageBucket: 'campuscar-fa0ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhxMXg4PNBIb1F5QxdrPlIs1wvVZyp28E',
    appId: '1:1073745768330:ios:65a26a70f210123d976273',
    messagingSenderId: '1073745768330',
    projectId: 'campuscar-fa0ef',
    storageBucket: 'campuscar-fa0ef.appspot.com',
    iosBundleId: 'com.example.vehicleIdentification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhxMXg4PNBIb1F5QxdrPlIs1wvVZyp28E',
    appId: '1:1073745768330:ios:9a98b8a065d01a25976273',
    messagingSenderId: '1073745768330',
    projectId: 'campuscar-fa0ef',
    storageBucket: 'campuscar-fa0ef.appspot.com',
    iosBundleId: 'com.example.vehicleIdentification.RunnerTests',
  );
}
